### ISSUE TITLE
Combining Features of Swin Transformer and other Features  

### ISSUE THREAD

**Issue by adeljalalyousif** [GX77/Dual-Stream-Transformer-for-Generic-Event-Boundary-Captioning#1]
Hello, thank you for sharing your code. Can you help me in this scenario:
For a video captioning model, I have sampled each video with 16 frames. I've employed a Video Swin Transformer to extract video features, resulting in a tensor of shape (batch_size, 768, 4, 7, 7). Additionally, I've used a 2D-CNN to extract frame-level features, resulting in a tensor of shape (batch_size, 16, 768). Now, I need to concatenate these two sets of features to create a combined representation with a shape like (batch_size, seq_len, feat_dim ) or similar, in order to use them with a traditional transformer encoder-decoder (self-attention and multi-headed attention). How can I achieve this concatenation for seamless integration into the model?
or simply how the word embedding vector (batch_size, seq_len, word_dim) and the Swin tensor (batch_size, 768, 4, 7, 7) are preprocessed before passing them to self-attention or multi-headed attention blocks of the traditional transformer

**Comment by GX77** [comment]
You have two sets of features:
(1) Video-level features of shape (batch_size, 768, 4, 7, 7)
(2) Frame-level features of shape (batch_size, 16, 768)

First, you need to flatten your video-level features to match the dimensionality of your frame-level features. This can be done by reshaping the tensor from (batch_size, 768, 4, 7, 7) to (batch_size, 768, 196) where 196 is the product of 4*7*7.
Then, you can concatenate the two feature sets along the sequence length dimension. However, note that the sequence length of your video-level features is 196, while for your frame-level features it is 16. You'll need to interpolate or otherwise adjust these to be the same.
One possible way to do this is to average the video-level features along the sequence length dimension, resulting in a tensor of shape (batch_size, 768). You can then expand this to (batch_size, 16, 768) by repeating the averaged features 16 times along the sequence length dimension.
Then you can concatenate the frame-level features and the modified video-level features along the feature dimension, resulting in a tensor of shape (batch_size, 16, 768*2).

GX
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GX77/Dual-Stream-Transformer-for-Generic-Event-Boundary-Captioning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 下午3:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[GX77/Dual-Stream-Transformer-for-Generic-Event-Boundary-Captioning] Combining Features of Swin Transformer and other Features   (Issue #1)





 
Hello, thank you for sharing your code. Can you help me in this scenario:
 For a video captioning model, I have sampled each video with 16 frames. I've employed a Video Swin Transformer to extract video features, resulting in a tensor of shape (batch_size, 768, 4, 7, 7). Additionally, I've used a 2D-CNN to extract frame-level features, resulting in a tensor of shape (batch_size, 16, 768). Now, I need to concatenate these two sets of features to create a combined representation with a shape like (batch_size, seq_len, feat_dim ) or similar, in order to use them with a traditional transformer encoder-decoder (self-attention and multi-headed attention). How can I achieve this concatenation for seamless integration into the model?

**Comment by adeljalalyousif** [comment]
Thank you so much
